version: '2'
services:
    # ----- CLI
    cli:
        container_name: goscan_cli
        build: cli/
        restart: always
        volumes:
            - ./_data/:/data/goscan/
            - ./goscan/:/go/src/github.com/marco-lancini/goscan
        command: /bin/bash
        stdin_open: true
        tty: true
        environment:
            GOSCAN_OUT_FOLDER: /data/goscan/
            GOSCAN_DB_PATH: /data/goscan/goscan.db
            RABBITMQ_URI: amqp://guest:guest@localhost:5672/
            DEBUG: 0
